trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd $(Build.SourcesDirectory)
    chmod +x ./init.sh
    ./init.sh

    cd testzeus-hercules-tests
    echo "testzeus-hercules" | comando


  displayName: